### ISSUE TITLE
Missing support python module(s)/libraries for fsleyes in fsl 6.0.1

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#271] opened 2019-03-21 15:32 UTC
Image was generated using
```bash
docker run -it --rm kaczmarj/neurodocker:master \
   generate singularity \
	--base=neurodebian:stretch \
	--fsl version=6.0.1 \
       -p apt \
	| sed  -e 's,/tmp/\* /var/tmp/\*,,g' \
	>| Singularity
```

env var for USER was adjusted per #270 by a call `source ~/set_user ` below.

```shell
$> singularity run -e -H /tmp/home ./fslanal
Some packages in this Docker container are non-free
If you are considering commercial use of this container, please consult the relevant license:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence
yoh@hopa:/home/yoh/proj/repronim/neurodocker-cases$ source ~/set_user 
yoh@hopa:/home/yoh/proj/repronim/neurodocker-cases$ DISPLAY=:0 fsleyes
Could not import wx
Traceback (most recent call last):
  File "fsl/utils/platform.py", line 159, in __init__
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/__init__.py", line 17, in <module>
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/core.py", line 12, in <module>
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "entrypt.py", line 146, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/__init__.py", line 208, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/plugins.py", line 176, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/views/viewpanel.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/__init__.py", line 12, in <module>
AttributeError: module 'wx' has no attribute '__version__'
[7988] Failed to execute script entrypt
```
I think the last one is the culprit: `AttributeError: module 'wx' has no attribute '__version__'`, and likely it is "upstream" issue for 6.0.1 release, and I didn't find a workaround yet, smth similar here https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;f2962d60.1812 was not applicable since I do not see any `libfreetype*`.  May be @pauldmccarthy has an immediate idea?

**Comment by pauldmccarthy** [comment] 2019-03-21 15:37
Looks to me like `gtk2` isn't installed - the critical line is this:
```
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by kaczmarj** [comment] 2019-03-21 15:38
thank you @pauldmccarthy. @yarikoptic - i have not tested fsl 6.0.1 thoroughly. i should add some tests that include loading fslpython

**Comment by pauldmccarthy** [comment] 2019-03-21 15:44
An alternative option to using the standalone FSLeyes builds - fsleyes is now on conda-forge, so you could install it directly into the `fslpython` environment. This is the intent for future FSL releases. You'll probably still have to manually install `gtk2` and other low level dependencies though, as `conda` doesn't do everything.

**Comment by yarikoptic** [comment] 2019-03-21 16:01
Thanks @pauldmccarthy for the reply!

re `libgtk-x11-2.0.so.0` - I thought that may be it was trying to use gtk as a fallback after wx gave a trouble and that is just a confusing order of messages ;) I guess, if needed, it should have been bundled with fsl tarball.

re `fslpython environment`: is there a specific requirement to use such named environment?
Also, I do not see conda being bundled but there is a script to install the miniconda etc:

```
$ find /opt -iname *conda*
$ ls -l /opt/fsl-6.0.1/etc/fslconf/fslpython_install.sh
-rwxr-xr-x 1 7959 1999 6055 Feb 21 06:24 /opt/fsl-6.0.1/etc/fslconf/fslpython_install.sh
 ```
should I just try calling it after extracting the fsl tarball?

**Comment by pauldmccarthy** [comment] 2019-03-21 16:13
> I guess, if needed, it should have been bundled with fsl tarball.

I think I originally tried to bundle `gtk2`, but quickly ran into compatibility issues on CentOS across minor releases of the same major version. Figuring out what `.so` libraries can safely be bundled is a black art as far as I'm concerned! So FSLeyes assumes that low level dependencies like this are present (and they will be on any "normal" linux desktop installation).

> re fslpython environment: is there a specific requirement to use such named environment?

FSL 5.0.10 and newer come with a miniconda installation in `$FSLDIR/fslpython/`, with a conda environment set up, also called `fslpython`. The `fslpython` command points to the `python` interpreter in this `fslpython` environment, and Python-based FSL tools are executed using this environment.

It should get installed when you run `fslinstaller.py` (if that is how you installed FSL), although has been known to fail without warning on flaky net connections. You should be able to install it via the `fslpython_install.sh` script. There's no need to use it, but it's there if you want to.

**Comment by yarikoptic** [comment] 2019-03-21 16:32
> I think I originally tried to bundle `gtk2`, but quickly ran into compatibility issues on CentOS across minor releases of the same major version.

semi-related: I wondered if may be http://nuitka.net could be of help to provide alternative building/bundling?  Personally, I've tried it a few times for DataLad but it was not yet (last year?) fully grasping all our complexities ;)  But Kay is very active and said that he addressed many related issues.  So might even just work for fsleyes?

**Comment by pauldmccarthy** [comment] 2019-03-21 17:02
Currently I use pyinstaller for linux, and py2app for mac. I guess nukita might improve performance of the python bits, although they're not really where the bottlenecks lie. Will take a look at it though - thanks!

**Comment by yarikoptic** [comment] 2019-04-03 14:23
@kaczmarj so what do you think should be done at neurodocker level to get FSL fully function? 
e.g. it could've removed traces of fsleyes and miniconda/pip installed fsleyes, or make use of the `fslinstaller.py`, or ...?

**Comment by kaczmarj** [comment] 2019-04-09 00:33
@yarikoptic - let me test this out. i'd like to go the `fslpython_install.sh` route.

**Comment by yarikoptic** [comment] 2019-04-09 03:34
thanks in advance!

**Comment by yarikoptic** [comment] 2019-07-23 21:02
@kaczmarj did you have any luck?  I have now ran into a similar gotcha, which is described on https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation#imcp.2Fimglob.2Fimmv_errors_after_installation as yet another problem with installation of python based components

**Comment by pauldmccarthy** [comment] 2019-07-24 07:57
Hey @yarikoptic, which error are you getting? The one about missing `imcp`, `immv` etc, or the `Requirements.parse` error?

The first error (missing `imcp`) is generally caused by network connection drop-outs during the FSL miniconda installation - conda tends to make a large number of simultaneous connections to download each package that it needs to install; on slower connections, these connections can time-out and get dropped. 

To make things worse, it's difficult to tell when this occurs (although I didn't write that bit of the script, and haven't really investigated it further), so you can end up with an installation which appeared to succeed, but is incomplete. There's no way to control how many simultaneous connections conda will make; you can, however, bump-up the time-out period, e.g.:

`echo "remote_read_timeout_secs: 240.0" > ~/.condarc`

(more info at https://docs.conda.io/projects/conda/en/latest/configuration.html)

The `Requirements.parse` error is due to a breaking change in the way that conda interprets requirement strings. Prior to conda version ~4.5 (I can't remember precisely), `deprecation<=2.*,>=1.*'` was accepted as a valid requirement, but in later versions it isn't. The installation will succeed (and will install `deprecation 2.*`), but you then will get an error at run-time! 

I adjusted the requirement string in `fslpy` a while back (and this will be fixed for FSL 6.0.2, which is imminent), but the version which is installed for FSL 6.0.1 is pegged at an older `fslpy` version which contains the broken string. For 6.0.1, you have a couple of options to fix this:

1. Run this command after the FSL installation to force-install a version of `deprecation` which is compatible with the requirement string:

    $FSLDIR/fslpython/bin/conda install -n fslpython -c conda-forge deprecation==1.*

2. Use an alternative `$FSLDIR/etc/fslpython_environment.yml` which explicitly lists `deprecation==1.*`

**Comment by yarikoptic** [comment] 2019-07-24 16:09
> Hey @yarikoptic, which error are you getting? The one about missing `imcp`, `immv` etc, or the `Requirements.parse` error?

that elderly container is missing `fslpython/` folder entirely, so my error was about missing `imglob`. I will try to regenerate and if no changes - will add additional commands per your instructions. Thanks @pauldmccarthy

**Comment by yarikoptic** [comment] 2019-07-24 16:12
> this will be fixed for FSL 6.0.2, which is imminent

Great, any ETA to share?

**Comment by pauldmccarthy** [comment] 2019-07-25 08:18
> Great, any ETA to share?

I don't know precisely, but it should be within the next couple of weeks...

**Comment by yarikoptic** [comment] 2019-07-25 17:42
#289 is perspective PR, building image locally to see if all is good

@pauldmccarthy how could I verify that `deprecation` module issue doesn't happen at run time for me?

**Comment by pauldmccarthy** [comment] 2019-07-26 10:05
Basically you just have to invoke an entry point which depends on the buggy `deprecation` requirement string - `imglob`, `immv`, `imcp` etc etc. If you call any of them without arguments, they should return an exit code of 0.

**Comment by pauldmccarthy** [comment] 2019-07-26 10:10
Wait - scratch that - all of those commands return non-zero with no args. I'll get that changed for a future release.

You can however use one of `atlasq`, `atlasquery`, or `fsl_ents - they'll all return non-0 if everything is ok.

**Closed** 2019-08-02 17:02 UTC

**Comment by kaczmarj** [comment] 2019-08-02 17:03
I guess #289 added the _python_ support modules for fsleyes, but I am still running into errors running fsleyes. `libgtk-x11-2.0.so.0` will probably have to be installed, but I haven't tested that this is the only issue.

```
Could not import wx
Traceback (most recent call last):
  File "fsl/utils/platform.py", line 159, in __init__
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/__init__.py", line 17, in <module>
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/core.py", line 12, in <module>
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "entrypt.py", line 146, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/__init__.py", line 208, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/plugins.py", line 176, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fsleyes/views/viewpanel.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/build.venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "wxPython-4.0.3-py3.6-linux-x86_64.egg/wx/__init__.py", line 12, in <module>
AttributeError: module 'wx' has no attribute '__version__'
[439] Failed to execute script entrypt
```
