### ISSUE TITLE
SPM12: only Matlab 2017a is supported, but repo website only hosts 2018a

### ISSUE THREAD

**Issue by jona-sassenhagen** [kaczmarj/neurodocker#148] opened 2018-03-16 12:55 UTC
When installing SPM, http://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/dev/ does not host a precompiled R2017a SPM at the moment. However, neurodocker complains it only supports R2017a. See below for a MWE:

```
docker run --rm kaczmarj/neurodocker:v0.3.2 generate -b neurodebian -p apt --spm version=12 matlab_version=R2018a
Traceback (most recent call last):
  File "/usr/bin/neurodocker", line 11, in <module>
    load_entry_point('neurodocker', 'console_scripts', 'neurodocker')()
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 281, in main
    subparser_functions[namespace.subparser_name](namespace)
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 228, in generate
    df = Dockerfile(specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 457, in __init__
    self.cmd = self._create_cmd()
  File "/opt/neurodocker/neurodocker/generate.py", line 478, in _create_cmd
    chunks = _get_dockerfile_chunks(self.specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 436, in _get_dockerfile_chunks
    chunk = _get_dockerfile_chunk(instruction, options, specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 414, in _get_dockerfile_chunk
    chunk = callable_(**options).cmd
  File "/opt/neurodocker/neurodocker/interfaces/spm.py", line 62, in __init__
    raise ValueError("Only MATLAB R2017a is supported (for now).")
ValueError: Only MATLAB R2017a is supported (for now).
```

**Comment by kaczmarj** [comment] 2018-03-16 12:59
Hi @jona-sassenhagen - thanks for the report. I am aware of this issue and am fixing it in #143. The Matlab version that the SPM version is compiled for will be downloaded.

**Comment by jona-sassenhagen** [comment] 2018-03-16 13:00
Thanks! Shall I close?

**Comment by kaczmarj** [comment] 2018-03-16 13:01
Nope, let's wait until the fix is merged.

**Comment by jona-sassenhagen** [comment] 2018-03-27 22:07
Closed by #2498?

**Comment by kaczmarj** [comment] 2018-03-27 22:10
@jona-sassenhagen - unfortunately not. that PR is a workaround for this bug. i apologize, i haven't had time to work on this yet.

**Comment by jona-sassenhagen** [comment] 2018-03-27 22:11
Np probs!

**Comment by kaczmarj** [comment] 2018-04-26 13:50
@jona-sassenhagen - this should be fixed by #159.

**Closed by kaczmarj** 2018-04-26 13:50 UTC

**Comment by kaczmarj** [comment] 2018-04-27 12:33
did you `pip install neurodocker`? it could be that pip does not install the required YAML files (which include the installation templates). i'll try in a fresh miniconda environment.

it's my first time packaging with pip :)

**Comment by jona-sassenhagen** [comment] 2018-04-27 12:55
>did you pip install neurodocker?

I think I am using `master`. Errrr. I should try with 0.4.0rc0 right?

**Comment by kaczmarj** [comment] 2018-04-27 12:57
@jona-sassenhagen - the problem is on neurodocker's end. `yaml` files are not included when `pip` installing by default. i'm updating the `setup.py` file to fix that now.

**Comment by jona-sassenhagen** [comment] 2018-04-27 13:00
Great.

**Comment by kaczmarj** [comment] 2018-04-27 15:47
@jona-sassenhagen - this is fixed now.

can you `pip install -U neurodocker`? the yaml files should be included now. feel free to open a new issue if you run into problems.
