### ISSUE TITLE
fsl exclude_paths does not work

### ISSUE THREAD

**Issue by xaviergp** [kaczmarj/neurodocker#215] opened 2018-08-03 23:13 UTC
I believe fsl exclude_paths does not work:

docker.exe run --rm kaczmarj/neurodocker:master generate "docker" \
  --base=neurodebian:stretch-non-free \
  --pkg-manager=apt \
  --install connectome-workbench \
  --freesurfer version=6.0.0-min exclude_paths='average trctrain subjects'\
  --miniconda create_env=neuro \
  conda_install="python=3.6 numpy seaborn nibabel jupyter nilearn" activate=true \
  pip_install="https://github.com/mgxd/niwidgets/archive/fix/inst.zip" \
  --fsl version=5.0.10 exclude_paths= 'extras fslpython data'\
  --workdir='/src' \
  --user root \
  --add-to-entrypoint="bash" > dockerfile
 
docker.exe build -t gradmap_neurodocker_v20 .

docker.exe run -interactive gradmap_neurodocker_v20

cd /opt/freesurfer-6.0.0-min #here you can see that the following folders are no longer included: average, trctrain, subjects

cd /opt/fsl-5.0.10 #here you can see that the following folders are STILL INCLUDED: extras, fslpython, data

**Comment by kaczmarj** [comment] 2018-08-04 18:10
@xaviergp - i can partially reproduce this. the fsl directories `extras` and `data` are not part of the container, when using the latest version of neurodocker (delete and repull the docker master docker image maybe). however, `fslpython` is there, and that is because fsl installs it's own python installation. it must be required for some fsl functionality. for the time being, to not include `fslpython`, you can manually remove the fslpython installation from the dockerfile, as below. please let me know if this works for you.

ORIGINAL
```dockerfile
    && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $ND_ENTRYPOINT \
    && echo "Installing FSL conda environment ..." \
    && bash /opt/fsl-5.0.10/etc/fslconf/fslpython_install.sh -f /opt/fsl-5.0.10
```

NEW
```dockerfile
    && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $ND_ENTRYPOINT
```

**Comment by kaczmarj** [comment] 2018-08-06 17:56
@xaviergp - i think I know what the issue is... there is a space between `exclude_paths=` and the paths you want to exclude. based on the way the command-line arguments are parsed, the space will mean that the paths are not treated as the arguments for `exclude_paths`. i will try to fix this sometime soon as it's a major issue.

can you try your command again, but remove the space between `exclude_paths=` and the paths?

**Comment by xaviergp** [comment] 2018-08-06 22:29
It works after erasing the space, thanks!

**Comment by kaczmarj** [comment] 2018-08-06 22:30
@xaviergp - excellent! i'll close this issue, but please reopen or open a new issue if necessary.

**Closed by kaczmarj** 2018-08-06 22:30 UTC
